version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-techchallenge
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: techchallenge
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build: .
    container_name: api-techchallenge
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 123456
      DB_NAME: techchallenge
      DB_PORT: 3306
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]

volumes:
  mysql-data:
